config/routes.rb
Quizzimoto::Application.routes.draw do
  resources :quizzes do
    get 'video_search'
    post 'video_search'
  end

  match "oauth2authorize" => "oauth2#authorize", :as => :oauth2_authorize
  match "oauth2callback"  => "oauth2#callback",  :as => :oauth2_callback
  match "logout"          => "oauth2#logout",    :as => :logout

  root :to => "quizzes#index"

end

app/controllers/quizzes_controller.rb
# Copyright 2012 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class QuizzesController < ApplicationController
  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz = Quiz.find(params[:id])
  end

  def new
    @quiz = Quiz.new

    # Set a default.
    @quiz.country_alpha2 = 'US'
  end

  def edit
    @quiz = Quiz.find(params[:id])
    unless @quiz.video_id.blank?
      response = fetch_youtube_resource(
        :uri => 'https://gdata.youtube.com/feeds/api/videos/' +
                CGI::escape(@quiz.video_id) +
                '?v=2&alt=jsonc')
      if response.status != 200
        logger.warn("Couldn't load video: #{response.body}")
        @video_entry = nil
      else
        @video_entry = JSON.parse(response.body)
      end
    end
  end

  def create
    @quiz = Quiz.new(params[:quiz])
    @quiz.owner_id = current_user_id

    if @quiz.save
      redirect_to(edit_quiz_url(@quiz), :notice => 'Quiz was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @quiz = Quiz.find(params[:id])

    if @quiz.update_attributes(params[:quiz])
      if params[:keep_editing] == 'true'
        url = edit_quiz_url(@quiz)
      else
        url = @quiz
      end
      redirect_to(url, :notice => 'Quiz was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @quiz = Quiz.find(params[:id])
    @quiz.destroy
    redirect_to(quizzes_url)
  end

  def video_search
    @quiz = Quiz.find(params[:quiz_id])
    unless params[:q].blank?
      response = fetch_youtube_resource(
        :uri => 'https://gdata.youtube.com/feeds/api/videos?v=2&alt=jsonc&q=' +
                CGI::escape(params[:q]))
      @search_results = JSON.parse([response.body].to_json)
    end
  end
end

app/helpers/quizzes_helper.rb
# Copyright 2012 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<!--
  Copyright 2012 Google Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<%
  # This form is a bit tricky.  It's very simple for new quizzes, and fairly
  # complex for existing quizzes.
%>

<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id=error_explanation>
      <h2>
        <%= pluralize(@quiz.errors.count, "error") %>
        prohibited this quiz from being saved:
      </h2>

      <ul>
        <% @quiz.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Basic Settings</legend>

    <div class=field>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class=field>
      <%= f.label :min_age_years %>
      <%= f.text_field :min_age_years %> (years)
    </div>

    <div class=field>
      <%= f.label :country_alpha2 %>
      <%= f.country_select :country_alpha2 %>
    </div>

    <% if @quiz.new_record? %>
      <div class="indented_submit spacious_submit">
        <%= f.submit %>
      </div>
    <% end %>
  </fieldset>

  <% unless @quiz.new_record? %>
    <fieldset>
      <legend>Video</legend>

      <% if @quiz.video_id.blank? %>
        <p>This is no video associated with this quiz yet.</p>
      <% elsif @video_entry.blank? %>
        <p>Could not load video: <%= @quiz.video_id %></p>
      <% else %>
        <p>
          <%= link_to @video_entry['data']['title'],
                      @video_entry['data']['player']['default'],
                      :target => '_top' %>
        </p>
      <% end %>

      <p><%= link_to 'Search for a video', quiz_video_search_path(@quiz) %></p>
    </fieldset>

    <fieldset>
      <legend>Form</legend>

      <p>
        To setup a form for your quiz, go to
        <a href="https://docs.google.com">docs.google.com</a> and create a new
        form.  Once you have created the form, click More Actions &gt; Embed.
        Look at the snippet of code, and find just the formkey.  Enter that
        below.  This process is currently a bit manual, but I'm hoping to
        improve it in the days to come.
      </p>

      <div class=field>
        <%= f.label :form_id %>
        <%= f.text_field :form_id %>
      </div>
    </fieldset>

    <div class=spacious_submit>
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

app/views/quizzes/_welcome.html.erb
<!--
  Copyright 2012 Google Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<p>Welcome to Quizzimoto!</p>

<p>
  This application lets you build video-based quizzes.
</p>

app/views/quizzes/edit.html.erb
<!--
  Copyright 2012 Google Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<h3>Editing quiz</h3>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<!--
  Copyright 2012 Google Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<%= render 'quizzes/welcome' %>

<h3>Available Quizzes</h3>

<% if @quizzes.blank? %>
  <p>There are no quizzes yet.  Be the first to create one!</p>
<% else %>
  <% @quizzes.each_slice(3) do |quizzes| %>
    <div>
      <% quizzes.each do |quiz| %>
        <div class=quiz_cell>
          <%= link_to quiz.name, quiz %><br>
          <%= link_to image_tag("http://i.ytimg.com/vi/#{quiz.video_id}/default.jpg"),
                      quiz %><br>
          Age: <%= quiz.min_age_years %>+<br>
          Country: <%= Country[quiz.country_alpha2].name %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Create a new quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<!--
  Copyright 2012 Google Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<h3>New quiz</h3>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<!--
  Copyright 2012 Google Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<% if @quiz.form_id.blank? %>
  <h3><%= @quiz.name %></h3>

  <p>This is no form associated with this quiz yet.</p>
<% else %>
  <iframe width=760 height=968 frameborder=0 marginheight=0 marginwidth=0 class=form
    src="https://docs.google.com/spreadsheet/embeddedform?formkey=<%= @quiz.form_id %>">Loading...</iframe>
<% end %>

<% if @quiz.video_id.blank? %>
  <p>This is no video associated with this quiz yet.</p>
<% else %>
  <iframe width=560 height=315
    src="http://www.youtube.com/embed/<%= @quiz.video_id %>"
    frameborder=0 allowfullscreen class=player></iframe>
<% end %>

<p>
  <b>Age:</b>
  <%= @quiz.min_age_years %>+

  <b>Country:</b>
  <%= Country[@quiz.country_alpha2].name %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/video_search.html.erb
<!--
  Copyright 2012 Google Inc.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<h3>Video search</h3>

<%= form_tag({}, {:method => 'GET '}) do %>
  <%= text_field_tag :q, params[:q],
                     {:size              => 40,
                      'x-webkit-speech'  => '',
                      'x-webkit-grammar' => 'builtin:search'} %>
  <%= submit_tag 'Search' %>
<% end %>

<% unless params[:q].blank? %>

  <% if @search_results['data']['totalItems'].to_i.zero? %>

    <p>Your search did not match any videos.</p>
  <% else %>
    <ul>
      <% @search_results['data']['items'].each do |item| %>
        <li>
          <%= form_for(@quiz) do |f| %>
            <%= f.hidden_field :video_id, :value => item['id'] %>
            <%= hidden_field_tag :keep_editing, 'true' %>
            <%= submit_tag 'Use This Video', class: 'submit btn' %>
            <%= item['title'] %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>